config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "welcome/index"

  root "welcome#index"

  resources :docs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [ :show, :edit, :update, :destroy ]
def index
  @docs = Doc.all.order(created_at: :desc)
end

def show
end

def new
  @doc = current_user.docs.build
end

def create
  @doc = current_user.docs.build(doc_params)

  if @doc.save
    redirect_to @doc
  else
    render "new"
  end
end

def edit
end

def update
  if @doc.update(doc_params)
    redirect_to @doc
  else
    render "edit"
  end
end

def destroy
  @doc.destroy
  redirect_to docs_path
end

  private

    def find_doc
      @doc = Doc.find(params[:id])
    end

    def doc_params
      params.require(:doc).permit(:title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
=  simple_form_for @doc do |f|
  = f.input :title
  = f.input :content
  = f.button :submit

app/views/docs/edit.html.haml
%h1 Fix Doc!

=  render 'form'

= link_to "Cancel", doc_path

:css
  :root {
    font-family: 'Arial', sans-serif;
    background-color: #f4f4f4;
    color: #333;
    margin: 0;
    padding: 20px;
  }

  body {
    max-width: 800px;
    margin: auto;
    padding: 20px;
    background-color:rgb(196, 196, 196);
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(255, 255, 255, 0.1);
  }

  h1 {
    color: rgb(0, 183, 255);
    background-color: rgb(255, 255, 255);
    padding: 10px;
    border-radius: 5px;
  }

  p {
    font-size: 16px;
    line-height: 1.5;
  }

  a {
    font-size: 16px;
    padding: 10px;
    border-radius: 5px;
    border: 1px solid #ccc;
    width: 100%;
    box-sizing: border-box;
    width : 100%;
    font-weight: bold;
    color: #fff;
    background-color: #3498db;
    text-decoration: none;
    display : flex;
    text-align: center;
    justify-content : center;
    transition : font-size 0.3s ease;
  }
  label{
    font-size: 16px;
    margin-block: 10px;
    margin-left : 10px;
    font-weight: bold;
    display: block;
    color: #333;
  }

  a:hover {
    font-size : 18px;
  }
  input{
    font-size: 16px;
    padding: 10px;
    border-radius: 5px;
    border: 1px solid #ccc;
    width: 100%;
    box-sizing: border-box;
    margin-bottom : 10px;
  }
  input.btn{
    margin-top : 10px;
    background-color: #3498db;
    color: #fff;
    border: none;
    cursor: pointer;
    font-weight: bold;
    transition : background-color 0.3s ease, font-size 0.3s ease;
  }
  input.btn:hover{
    background-color: #2980b9;
    font-size: 18px;
  }
  textarea{
    font-size: 16px;
    padding: 10px;
    border-radius: 5px;
    border: 1px solid #ccc;
    width: 100%;
    box-sizing: border-box;
    height: 200px;
  }

app/views/docs/index.html.haml
-@docs.each  do |doc|
  %h2.titulo= link_to doc.title, doc
  %p= time_ago_in_words(doc.created_at)
  %p= truncate(doc.content, length: 50)
  
  = link_to "Create New Document", new_doc_path, class: "criarnovo"

:css
  :root {
    font-family: 'Arial', sans-serif;
    background-color: #f4f4f4;
    color: #333;
    margin: 0;
    padding: 20px;
  }
  body {
    max-width: 800px;
    margin: auto;
    padding: 20px;
    background-color:rgb(196, 196, 196);
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(255, 255, 255, 0.1);
  }
  h2.titulo{
    color: rgb(0, 183, 255);
    background-color: rgb(255, 255, 255);
    padding: 10px;
    border-radius: 5px;
  }
  h2.titulo a{
    text-transform : uppercase;
    font-size: 20px;
    font-weight: 900;
    color: #3498db;
  }
  a.criarnovo{
    font-size: 16px;
    padding: 10px;
    border-radius: 5px;
    border: 1px solid #ccc;
    width: 100%;
    box-sizing: border-box;
    width : 100%;
    font-weight: bold;
    color: #fff;
    background-color: #3498db;
    text-decoration: none;
    display : flex;
    text-align: center;
    justify-content : center;
    transition : font-size 0.3s ease;
  }

app/views/docs/new.html.haml
%h1 New Doc!

= render 'form'

app/views/docs/show.html.haml
%h1= @doc.title
%p.texto= @doc.content

= link_to "All Docs", docs_path
= link_to "Fix Doc", edit_doc_path(@doc)
= link_to "Trash", @doc, method: :delete, data: { confirm: "Are you sure about that?" }

:css
  :root {
    font-family: 'Arial', sans-serif;
    background-color: #f4f4f4;
    color: #333;
    margin: 0;
    padding: 20px;
  }

  body {
    max-width: 800px;
    margin: auto;
    padding: 20px;
    background-color:rgb(196, 196, 196);
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(255, 255, 255, 0.1);
  }

  h1 {
    color: rgb(0, 183, 255);
    background-color: rgb(255, 255, 255);
    padding: 10px;
    border-radius: 5px;
  }

  p.texto {
    background-color : rgb(255, 255, 255);
    padding: 10px;
    border-radius: 5px;
    font-size: 16px;
    line-height: 1.5;
  }

  a {
    font-size: 16px;
    padding: 10px;
    border-radius: 5px;
    border: 1px solid #ccc;
    width: 100%;
    box-sizing: border-box;
    width : 100%;
    font-weight: bold;
    color: #fff;
    background-color: #3498db;
    text-decoration: none;
    display : flex;
    text-align: center;
    justify-content : center;
    transition : font-size 0.3s ease;
  }

  a:hover {
    font-size : 18px;
  }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Cabinet" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>

    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.haml
%h1 Voila! This is the Placeholder!